workflows:
  android-workflow:
    name: Android Build
    environment:
      java: 17

    scripts:
      - name: Fix gradlew permission
        script: |
          ls -la
          chmod +x gradlew
          chmod +x ./gradlew
          ls -la

      - name: Build APK
        script: ./gradlew assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk
